version: 1.0.0-{branch}-{build}

environment:
  matrix:
    - RUBY_VERSION: 24-x64
      CAPYBARA_FF: true

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - cinst squashfs Firefox
  - '"C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\vcvarsall" x64'
  - appveyor DownloadFile http://enclose.io/rubyc/rubyc-x64.zip
  - 7z e rubyc-x64.zip
  - bundle install

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - "%BUNDLE_PATH%"
  - "%GEM_HOME%"

artifacts:
  - path: winapp-example.exe
    name: app

build_script:
  - rubyc-v0.4.0-x64.exe -o winapp-example.exe bin/rails

before_test:
  - bundle install --with development test
  - bundle exec rails db:setup db:test:prepare

test_script:
  - bundle exec rails test -e test --no-color
