version: 1.0.0-{branch}-{build}

image: Visual Studio 2017

environment:
  matrix:
    - RUBY_VERSION: 24-x64
      CAPYBARA_FF: true

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  # - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cinst winflexbison
  - ps: Copy-Item -path C:\ProgramData\chocolatey\lib\winflexbison\tools\win_bison.exe -destination C:\ProgramData\chocolatey\lib\winflexbison\tools\bison.exe
  - ps: |
      $ErrorActionPreference="Stop"
      dir C:\projects
      Start-FileDownload http://enclose.io/rubyc/rubyc-x64.zip -FileName C:\projects\rubyc-x64.zip
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\rubyc-x64.zip", "C:\projects\usr\bin")
      Rename-Item -path C:\projects\usr\bin\rubyc-v0.4.0-x64.exe -newname C:\projects\usr\bin\rubyc.exe
      Start-FileDownload https://github.com/pmq20/squashfuse/files/691217/sqfs43-win32.zip -FileName C:\projects\sqfs43-win32.zip
      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\sqfs43-win32.zip", "C:\projects\usr\bin")
      Start-FileDownload https://github.com/lexxmark/winflexbison/releases/download/v2.5.16/winflexbison-2.5.16.zip -FileName C:\projects\bison.zip
      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\bison.zip", "C:\projects\usr\bin")
      Rename-Item -path C:\projects\usr\bin\win_bison.exe -newname C:\projects\usr\bin\bison.exe
      Rename-Item -path C:\projects\usr\bin\win_flex.exe -newname C:\projects\usr\bin\flex.exe
  - cmd: |
      dir "C:\projects\usr\bin"
      set PATH=C:\projects\usr\bin;%PATH%
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64_x86
      where mksquashfs
      mksquashfs -version
      where ruby
      ruby --version
      where gem
      gem --version
      where bundle
      bundle --version
      where rubyc
      rubyc --version
      where bison
      bison --version
  - bundle install

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%BUNDLE_PATH%'
  - '%GEM_HOME%'

artifacts:
  - path: winapp-example.exe
    name: app

build_script:
  - rubyc -o winapp-example.exe bin/rails

before_test:
  - cinst Firefox
  - bundle install --with development test
  - bundle exec rails db:setup db:test:prepare

test_script:
  - bundle exec rails test -e test --no-color
